services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dhukuti-postgres-dev
    environment:
      POSTGRES_DB: dhukuti
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - dhukuti-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Development Server
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dhukuti-app-dev
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/dhukuti
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_NAME=Dhukuti
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dhukuti-network-dev
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  dhukuti-network-dev:
    driver: bridge 