services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dhukuti-postgres
    environment:
      POSTGRES_DB: dhukuti
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma:/docker-entrypoint-initdb.d
    networks:
      - dhukuti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhukuti-app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/dhukuti
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_NAME=Dhukuti
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dhukuti-network
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped

  # Prisma Studio (optional - for database management)
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhukuti-prisma-studio
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/dhukuti
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dhukuti-network
    command: npx prisma studio --hostname 0.0.0.0 --port 5555
    profiles:
      - tools

volumes:
  postgres_data:

networks:
  dhukuti-network:
    driver: bridge 