
# -----------------------------------------------------------------------------
# File: 0001_initial.py
# Description: Initial migration for Dhukuti core app. Creates Group model.
# Author: [Your Name]
# Created: 2025-07-13
# -----------------------------------------------------------------------------

# Generated by Django 5.2.4 on 2025-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    # -------------------------------------------------------------------------
    # Operations: Create Group model
    # -------------------------------------------------------------------------
    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("amount", models.PositiveIntegerField()),
                ("frequency", models.CharField(max_length=50)),
                ("members", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
            ],
        ),
    ]
